# -*- coding: utf-8 -*-
"""Banque de sujets éditoriaux — La Grande Vision.

Séparée du moteur (generer.py) pour rester facile à enrichir par un agent.
Chaque sujet : (pilier, sujet court). Persona, objectif, plateforme et formats
sont dérivés du pilier par le moteur. Le total dépasse 180 pour garantir l'unicité.
"""

# PIL1 — Pédagogie & Santé visuelle (Expert) — objectif notoriété/expertise
PIL1 = [
    "5 signes que vos lunettes ne sont plus adaptées",
    "Pourquoi vous avez mal à la tête devant l'écran",
    "Vos yeux sont secs ? Voici pourquoi",
    "La lumière bleue : mythe ou vrai danger ?",
    "À quel âge faire le premier bilan de vue de son enfant",
    "Votre enfant plisse les yeux : faut-il s'inquiéter ?",
    "Pourquoi vous voyez flou le soir",
    "Vision de près qui baisse après 40 ans : la presbytie expliquée",
    "Mythe : « porter des lunettes rend dépendant »",
    "Combien de temps dure une bonne paire de verres",
    "Astigmatisme, myopie, hypermétropie : la différence simple",
    "Pourquoi se frotter les yeux est une mauvaise idée",
    "La règle 20-20-20 pour reposer ses yeux",
    "Conduire de nuit devient difficile : ce que ça révèle",
    "Les écrans abîment-ils vraiment la vue des enfants ?",
    "Pourquoi un bilan de vue n'est pas qu'une question de lunettes",
    "Larmoiement, picotements : votre œil vous parle",
    "Le soleil et vos yeux : protéger sa vue toute l'année",
    "Pourquoi changer de lunettes tous les 1 à 2 ans",
    "Vision double : un signal à ne jamais ignorer",
    "Fatigue visuelle numérique : 6 réflexes simples",
    "Pourquoi vos anciennes lunettes vous fatiguent",
    "Diabète et vue : ce lien que peu connaissent",
    "Maux de tête en fin de journée : et si c'était vos yeux ?",
    "Bien éclairer son espace de travail pour ses yeux",
    "Lentilles ou lunettes : comment choisir",
    "Pourquoi la vue baisse sans qu'on s'en rende compte",
    "Les bons aliments pour la santé de vos yeux",
    "Écran de téléphone trop proche : le bon réflexe",
    "Sécheresse oculaire en saison sèche : que faire",
    "Reconnaître une vraie correction d'une devinette",
    "Vos yeux rougissent souvent : les causes fréquentes",
    "Pourquoi les enfants ne disent pas qu'ils voient mal",
    "Lire dans le noir abîme-t-il les yeux ?",
    "Le test simple à faire chez soi (et ses limites)",
    "Quand des lunettes de pharmacie ne suffisent plus",
    "Comprendre votre ordonnance de lunettes",
    "Pourquoi deux yeux peuvent avoir deux corrections",
    "Vision et réussite scolaire : le lien sous-estimé",
    "Halos autour des lumières la nuit : explication",
]

# PIL2 — Produits & Montures (Désir) — objectif vente
PIL2 = [
    "Comment choisir une monture selon la forme de son visage",
    "Nouvelle collection : les montures tendance de la saison",
    "Verres progressifs : voir de près et de loin sans changer de lunettes",
    "Les verres anti-lumière bleue, pour qui ?",
    "Montures fines vs épaisses : laquelle pour vous",
    "Verres amincis : légèreté et confort au quotidien",
    "Lunettes de soleil à votre vue : style et protection",
    "Traitement antireflet : pourquoi ça change tout",
    "Montures pour enfants : solides, légères, stylées",
    "Les couleurs de monture qui mettent votre teint en valeur",
    "Verres photochromiques : ils s'adaptent à la lumière",
    "Bien choisir ses lunettes de lecture",
    "Montures premium : la qualité qui dure",
    "Le bon poids de lunettes pour ne plus les sentir",
    "Verres pour écrans : le confort des pros connectés",
    "Lunettes de sport : tenir et protéger",
    "Comment entretenir ses lunettes pour qu'elles durent",
    "Montures pour petits budgets, grande allure",
    "L'essayage : trouvez LA paire qui vous ressemble",
    "Progressifs nouvelle génération : adieu le mal de tête",
    "Verres polarisants : la conduite sans éblouissement",
    "Deux paires, deux usages : travail et détente",
    "Les montures unisexes qui plaisent à tout le monde",
    "Pourquoi un verre sur mesure vaut mieux qu'un verre standard",
    "Lunettes et look : assortir ses montures à son style",
    "Montures intemporelles : l'élégance qui ne se démode pas",
    "Le confort des branches souples et flexibles",
    "Verres haute définition : la netteté maximale",
    "Choisir des lunettes quand on a un fort défaut visuel",
    "Les nouveautés montures pour homme cette saison",
    "Les nouveautés montures pour femme cette saison",
    "Lunettes anti-fatigue pour étudiants",
]

# PIL3 — Preuve sociale & Témoignages (Confiance)
PIL3 = [
    "Témoignage : « Avec mes progressifs, je revis »",
    "Avant / après : le confort d'une vraie correction",
    "Portrait : rencontrez votre opticien à La Grande Vision",
    "Ils nous ont fait confiance : merci à nos clients de Yopougon",
    "Témoignage d'une maman : le dépistage qui a sauvé l'année scolaire",
    "Un client raconte sa première paire chez nous",
    "Les coulisses d'un essayage réussi",
    "Pourquoi nos clients reviennent (et reviennent encore)",
    "Témoignage : un pro des écrans enfin soulagé",
    "Histoire d'une transformation : du flou à la netteté",
    "Nos clients notent leur expérience : la confiance en chiffres",
    "Une famille entière équipée chez La Grande Vision",
    "Témoignage : « J'avais peur des progressifs, j'avais tort »",
    "Le sourire d'un enfant qui voit enfin le tableau",
    "Merci pour vos avis 5 étoiles",
    "Rencontre avec notre équipe : des experts à votre écoute",
    "Un client B2B partage son partenariat avec nous",
    "Témoignage : un service premium, de l'accueil au suivi",
]

# PIL4 — Offres & Conversion (Action) — objectif RDV/vente
PIL4 = [
    "Réservez votre bilan de vue en 2 clics sur WhatsApp",
    "Cette semaine : prenez RDV pour votre consultation visuelle",
    "Offre rentrée : pensez à la vue de vos enfants",
    "Besoin de nouvelles lunettes ? Écrivez-nous sur WhatsApp",
    "Forfait verres progressifs : confort et clarté",
    "Dépistage : et si vous faisiez vérifier votre vue ?",
    "RDV express : votre bilan sans attendre",
    "Vos yeux fatiguent au travail ? Parlons-en",
    "Offre famille : équipez toute la maison",
    "Nouvelle correction ? Faites le point avec nous",
    "Promo montures : le style à petit prix",
    "Réservez votre essayage personnalisé",
    "Bilan de vue : le premier pas vers un vrai confort",
    "Verres anti-lumière bleue : protégez vos yeux d'écran",
    "Un cadeau qui change la vie : offrez un bilan de vue",
    "Spécial presbytie : découvrez nos progressifs",
    "Vos lunettes sont rayées ? Renouvelez-les facilement",
    "Prenez soin de vos yeux avant la rentrée",
    "RDV du week-end : on s'occupe de votre vue",
    "Offre étudiante : voir clair pour mieux réussir",
    "Lunettes de soleil à votre vue : commandez maintenant",
    "Votre seconde paire à prix doux",
    "Consultation + conseils montures : tout en une visite",
    "Écrivez « VUE » sur WhatsApp et on s'occupe du reste",
    "Profitez de l'offre du mois sur les verres premium",
    "Faites contrôler la vue de vos parents",
    "Réservez avant la fin de la semaine",
    "Bilan offert pour tout achat de monture",
    "Nouvelle collection : venez l'essayer ce week-end",
    "Un RDV aujourd'hui, des yeux reposés demain",
]

# PIL5 — Vie locale & Communauté (Proximité)
PIL5 = [
    "Fiers d'être votre opticien à Yopougon",
    "Rentrée scolaire à Yopougon : pensez aux yeux des enfants",
    "La Grande Vision au cœur de votre quartier",
    "Bonne fête à toutes les mamans de Yopougon",
    "Yopougon, on prend soin de votre vue",
    "Notre cabinet, un lieu de confiance pour les familles",
    "Saison des fêtes : voyez la vie en grand",
    "Soutien à la communauté : la santé visuelle pour tous",
    "Venez nous rencontrer : voici comment nous trouver",
    "Merci Yopougon pour votre confiance",
    "La santé visuelle, une affaire de quartier",
    "Nouvel an : et si vous preniez soin de vos yeux ?",
    "Journée mondiale de la vue : agissons ensemble",
    "Nos horaires pour mieux vous servir",
    "Un accueil chaleureux vous attend",
    "Fête des pères : offrez le confort de bien voir",
    "Vacances et soleil : protégez les yeux de la famille",
    "Près de chez vous, des experts à votre écoute",
]

# PIL6 — Coulisses & Expertise B2B (Autorité pro)
PIL6 = [
    "Dans les coulisses : comment se déroule un bilan de vue",
    "La technologie qui mesure votre vue avec précision",
    "Offre entreprise : la santé visuelle de vos salariés",
    "Comment nous fabriquons une paire sur mesure",
    "Mutuelles & entreprises : devenez partenaire",
    "Le parcours qualité d'une commande, de A à Z",
    "Pourquoi un opticien diplômé fait la différence",
    "Dépistage en entreprise : prévenir la fatigue des équipes",
    "Notre exigence : des verres contrôlés un par un",
]

BANQUE = {
    "PIL1": PIL1, "PIL2": PIL2, "PIL3": PIL3,
    "PIL4": PIL4, "PIL5": PIL5, "PIL6": PIL6,
}
